export interface Village {
  id: number;
  name: string;
  slug: string;
  direction: string;
  distance: number;
  readiness: number;
  description: string;
  features: string[];
  priceFrom: number;
  plotsCount: number;
  plotsAvailable: number;
  areaFrom: number;
  areaTo: number;
  photos: string[];
  coords: [number, number];
  plots?: Plot[];
  /** UUID for map.zemexx.ru interactive plot map API (optional) */
  mapUuid?: string;
  /** Full iframe URL for villages that use an external map widget */
  iframeMapUrl?: string;
}

export interface Plot {
  id: number;
  number: string;
  area: number;
  price: number;
  status: "available" | "reserved" | "sold";
}

// Base URL for zemexx.ru images (full-size originals via Bitrix iblock)
const Z = "http://zemexx.ru/upload/iblock";
// Base URL for zemexx.ru resized images (Bitrix resize_cache)
const ZR = "http://zemexx.ru/upload/resize_cache/iblock";

export const villages: Village[] = [
  {
    id: 1,
    name: "Фаворит",
    slug: "favorit",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=bbefc754-d030-11eb-944a-ac1f6b478593",
    direction: "Каширское шоссе",
    distance: 30,
    readiness: 99,
    description: "Готовый коттеджный посёлок с полной инфраструктурой. Газ, электричество, асфальтированные дороги, охрана, детская площадка. Рядом хвойный лес и река.",
    features: ["Газ", "Электричество", "Асфальт", "Охрана", "Детская площадка", "Хвойный лес", "Река"],
    priceFrom: 490000,
    plotsCount: 57,
    plotsAvailable: 12,
    areaFrom: 6,
    areaTo: 12,
    photos: [
      `/villages/favorit/02.jpg`,
      `/villages/favorit/01.jpg`,
      `/villages/favorit/03.jpg`,
      `/villages/favorit/04.jpg`,
      `/villages/favorit/05.jpg`,
      `/villages/favorit/06.jpg`,
      `/villages/favorit/07.jpg`,
      `/villages/favorit/08.jpg`,
    ],
    coords: [55.3250, 37.8650],
    plots: [
      { id: 101, number: "12", area: 6, price: 490000, status: "available" },
      { id: 102, number: "15", area: 8, price: 490000, status: "available" },
      { id: 103, number: "23", area: 10, price: 485000, status: "reserved" },
      { id: 104, number: "31", area: 12, price: 480000, status: "available" },
      { id: 105, number: "44", area: 6, price: 495000, status: "sold" },
    ],
  },
  {
    id: 2,
    name: "Лесной остров",
    slug: "lesnoy-ostrov",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=624188a3-dfe8-11ec-8e96-00155d7faf0b",
    direction: "Каширское шоссе",
    distance: 36,
    readiness: 100,
    description: "Полностью готовый посёлок в окружении леса. Все коммуникации подведены, дороги с твёрдым покрытием, круглосуточная охрана.",
    features: ["Газ", "Электричество", "Асфальт", "Охрана", "Лес", "Все коммуникации"],
    priceFrom: 625000,
    plotsCount: 57,
    plotsAvailable: 8,
    areaFrom: 6,
    areaTo: 10,
    photos: [
      `/villages/lesnoy-ostrov/01.jpg`,
      `/villages/lesnoy-ostrov/02.jpg`,
      `/villages/lesnoy-ostrov/03.jpg`,
      `/villages/lesnoy-ostrov/04.jpg`,
      `/villages/lesnoy-ostrov/05.jpg`,
      `/villages/lesnoy-ostrov/06.jpg`,
      `/villages/lesnoy-ostrov/07.jpg`,
      `/villages/lesnoy-ostrov/08.jpg`,
    ],
    coords: [55.2780, 37.8200],
    plots: [
      { id: 201, number: "5", area: 6, price: 625000, status: "available" },
      { id: 202, number: "18", area: 8, price: 620000, status: "available" },
      { id: 203, number: "27", area: 10, price: 615000, status: "reserved" },
    ],
  },
  {
    id: 3,
    name: "Новое Сонино",
    slug: "novoe-sonino",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=8917e6e6-301c-11ec-944b-ac1f6b478593",
    direction: "Каширское шоссе",
    distance: 37,
    readiness: 100,
    description: "Живописный посёлок у реки Злодейка в окружении векового леса. Полностью обеспечен коммуникациями.",
    features: ["Газ", "Электричество", "Асфальт", "Река", "Вековой лес", "Все коммуникации"],
    priceFrom: 355000,
    plotsCount: 33,
    plotsAvailable: 10,
    areaFrom: 6,
    areaTo: 12,
    photos: [
      `/villages/novoe-sonino/01.jpg`,
      `/villages/novoe-sonino/03.jpg`,
      `/villages/novoe-sonino/04.jpg`,
      `/villages/novoe-sonino/05.jpg`,
      `/villages/novoe-sonino/06.jpg`,
      `/villages/novoe-sonino/07.jpg`,
      `/villages/novoe-sonino/08.jpg`,
    ],
    coords: [55.2600, 37.7900],
    plots: [
      { id: 301, number: "3", area: 6, price: 360000, status: "available" },
      { id: 302, number: "11", area: 8, price: 355000, status: "available" },
      { id: 303, number: "19", area: 10, price: 350000, status: "available" },
      { id: 304, number: "25", area: 12, price: 345000, status: "reserved" },
    ],
  },
  {
    id: 4,
    name: "ПриЛесной",
    slug: "prilesnoy",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=6aa3930b-95a2-11ee-b3ad-005056a6b235",
    direction: "Дмитровское шоссе",
    distance: 27,
    readiness: 75,
    description: "Посёлок бизнес-класса на Дмитровском направлении. Отличная транспортная доступность, рядом лес.",
    features: ["Газ", "Электричество", "Асфальт", "Охрана", "Лес", "Близость к Москве"],
    priceFrom: 1360000,
    plotsCount: 29,
    plotsAvailable: 22,
    areaFrom: 8,
    areaTo: 15,
    photos: [
      `/villages/prilesnoy/01.jpg`,
      `/villages/prilesnoy/02.jpg`,
      `/villages/prilesnoy/03.jpg`,
      `/villages/prilesnoy/04.jpg`,
      `/villages/prilesnoy/05.jpg`,
      `/villages/prilesnoy/06.jpg`,
      `/villages/prilesnoy/07.jpg`,
      `/villages/prilesnoy/08.jpg`,
    ],
    coords: [55.9800, 37.5600],
    plots: [
      { id: 401, number: "2", area: 8, price: 1360000, status: "available" },
      { id: 402, number: "7", area: 10, price: 1350000, status: "available" },
      { id: 403, number: "14", area: 15, price: 1340000, status: "reserved" },
    ],
  },
  {
    id: 5,
    name: "Дачная Практика-2",
    slug: "dachnaya-praktika-2",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=c6f9bc67-b4f1-11ec-8e96-00155d7faf0b",
    direction: "Каширское шоссе",
    distance: 42,
    readiness: 100,
    description: "Готовый посёлок с ограждением и круглосуточной охраной. Все коммуникации подведены к каждому участку.",
    features: ["Газ", "Электричество", "Асфальт", "Охрана", "Ограждение", "Все коммуникации"],
    priceFrom: 400000,
    plotsCount: 81,
    plotsAvailable: 15,
    areaFrom: 6,
    areaTo: 12,
    photos: [
      `/villages/dachnaya-praktika-2/01.jpg`,
      `/villages/dachnaya-praktika-2/02.jpg`,
      `/villages/dachnaya-praktika-2/03.jpg`,
      `/villages/dachnaya-praktika-2/04.jpg`,
      `/villages/dachnaya-praktika-2/05.jpg`,
      `/villages/dachnaya-praktika-2/06.jpg`,
      `/villages/dachnaya-praktika-2/07.jpg`,
      `/villages/dachnaya-praktika-2/08.jpg`,
    ],
    coords: [55.2200, 37.8100],
    plots: [
      { id: 501, number: "8", area: 6, price: 405000, status: "available" },
      { id: 502, number: "22", area: 8, price: 400000, status: "available" },
      { id: 503, number: "35", area: 10, price: 395000, status: "available" },
      { id: 504, number: "47", area: 12, price: 390000, status: "reserved" },
      { id: 505, number: "60", area: 6, price: 410000, status: "sold" },
    ],
  },
  {
    id: 6,
    name: "Шишкино Лэнд",
    slug: "shishkino-land",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=46d569bf-0651-11f0-b3bf-005056a6b235",
    direction: "Каширское шоссе",
    distance: 41,
    readiness: 60,
    description: "Посёлок с развитой инфраструктурой: магазины, кафе, школы и спортивные объекты в пешей доступности.",
    features: ["Газ", "Электричество", "Асфальт", "Магазины", "Школы", "Спортплощадки"],
    priceFrom: 465000,
    plotsCount: 63,
    plotsAvailable: 32,
    areaFrom: 6,
    areaTo: 10,
    photos: [
      `/villages/shishkino-land/01.jpg`,
      `/villages/shishkino-land/02.jpg`,
      `/villages/shishkino-land/03.jpg`,
      `/villages/shishkino-land/04.jpg`,
      `/villages/shishkino-land/05.jpg`,
      `/villages/shishkino-land/06.jpg`,
      `/villages/shishkino-land/07.jpg`,
      `/villages/shishkino-land/08.jpg`,
    ],
    coords: [55.2300, 37.7800],
    plots: [
      { id: 601, number: "4", area: 6, price: 470000, status: "available" },
      { id: 602, number: "16", area: 8, price: 465000, status: "available" },
      { id: 603, number: "28", area: 10, price: 460000, status: "available" },
    ],
  },
  {
    id: 7,
    name: "Триумфальный",
    slug: "triumfalnyy",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=71f88ce4-8f8a-11ee-b3a8-005056a6b235",
    direction: "Дмитровское шоссе",
    distance: 28,
    readiness: 77,
    description: "Крупный посёлок на Дмитровском направлении с удобной транспортной доступностью и развитой инфраструктурой.",
    features: ["Газ", "Электричество", "Асфальт", "Охрана", "Транспорт"],
    priceFrom: 1040000,
    plotsCount: 128,
    plotsAvailable: 30,
    areaFrom: 6,
    areaTo: 12,
    photos: [
      `/villages/triumfalnyy/01.jpg`,
      `/villages/triumfalnyy/02.jpg`,
      `/villages/triumfalnyy/03.jpg`,
      `/villages/triumfalnyy/04.jpg`,
      `/villages/triumfalnyy/05.jpg`,
      `/villages/triumfalnyy/06.jpg`,
      `/villages/triumfalnyy/07.jpg`,
      `/villages/triumfalnyy/08.jpg`,
    ],
    coords: [55.9700, 37.5400],
    plots: [
      { id: 701, number: "10", area: 6, price: 1050000, status: "available" },
      { id: 702, number: "33", area: 8, price: 1040000, status: "available" },
      { id: 703, number: "55", area: 10, price: 1035000, status: "reserved" },
      { id: 704, number: "77", area: 12, price: 1030000, status: "available" },
    ],
  },
  {
    id: 8,
    name: "РигаЛес",
    slug: "rigales",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=c52980b2-ce5d-11ef-b3b6-005056a6b235",
    direction: "Новорижское шоссе",
    distance: 45,
    readiness: 64,
    description: "Премиальный посёлок на Новорижском направлении в окружении леса. Престижная локация для загородной жизни.",
    features: ["Газ", "Электричество", "Асфальт", "Охрана", "Лес", "Премиум"],
    priceFrom: 1799000,
    plotsCount: 10,
    plotsAvailable: 4,
    areaFrom: 10,
    areaTo: 20,
    photos: [
      `/villages/rigales/01.jpg`,
      `/villages/rigales/02.jpg`,
      `/villages/rigales/03.jpg`,
      `/villages/rigales/04.jpg`,
      `/villages/rigales/05.jpg`,
      `/villages/rigales/06.jpg`,
      `/villages/rigales/07.jpg`,
      `/villages/rigales/08.jpg`,
    ],
    coords: [55.8100, 36.9800],
    plots: [
      { id: 801, number: "1", area: 10, price: 1800000, status: "available" },
      { id: 802, number: "3", area: 15, price: 1799000, status: "available" },
      { id: 803, number: "6", area: 20, price: 1790000, status: "reserved" },
    ],
  },
  {
    id: 9,
    name: "Рэд",
    slug: "red",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=4e3bb69b-b334-11eb-9448-ac1f6b478593",
    direction: "Каширское шоссе",
    distance: 35,
    readiness: 90,
    description: "Современный посёлок с продуманной планировкой. GPS: N 55.320993 E 37.794129. Все коммуникации подведены.",
    features: ["Газ", "Электричество", "Асфальт", "Охрана", "Современная планировка"],
    priceFrom: 550000,
    plotsCount: 45,
    plotsAvailable: 10,
    areaFrom: 6,
    areaTo: 12,
    photos: [
      `/villages/red/01.jpg`,
      `/villages/red/02.jpg`,
      `/villages/red/03.jpg`,
      `/villages/red/04.jpg`,
      `/villages/red/05.jpg`,
      `/villages/red/06.jpg`,
      `/villages/red/07.jpg`,
      `/villages/red/08.jpg`,
    ],
    coords: [55.3210, 37.7941],
    plots: [
      { id: 901, number: "5", area: 6, price: 555000, status: "available" },
      { id: 902, number: "12", area: 8, price: 550000, status: "available" },
      { id: 903, number: "20", area: 10, price: 545000, status: "reserved" },
    ],
  },
  {
    id: 10,
    name: "Каретный ряд",
    slug: "karetnyy-ryad",
    direction: "Новорижское шоссе",
    distance: 50,
    readiness: 70,
    description: "Посёлок на Новорижском направлении. 128 участков, развитая инфраструктура, удобная транспортная доступность.",
    features: ["Газ", "Электричество", "Асфальт", "Охрана", "Новорижское направление"],
    priceFrom: 950000,
    plotsCount: 128,
    plotsAvailable: 56,
    areaFrom: 6,
    areaTo: 12,
    photos: [
      `/villages/karetnyy-ryad/01.jpg`,
      `/villages/karetnyy-ryad/02.jpg`,
      `/villages/karetnyy-ryad/03.jpg`,
      `/villages/karetnyy-ryad/04.jpg`,
      `/villages/karetnyy-ryad/05.jpg`,
      `/villages/karetnyy-ryad/06.jpg`,
      `/villages/karetnyy-ryad/07.jpg`,
      `/villages/karetnyy-ryad/08.jpg`,
    ],
    coords: [55.7972, 36.7976],
    mapUuid: "b89b431c-c28e-11ef-b3b6-005056a6b235",
    plots: [
      { id: 1001, number: "117", area: 6.8, price: 950000, status: "available" },
      { id: 1002, number: "45", area: 8, price: 998000, status: "available" },
      { id: 1003, number: "78", area: 10, price: 1055000, status: "reserved" },
      { id: 1004, number: "92", area: 12, price: 1149000, status: "sold" },
    ],
  },
  {
    id: 11,
    name: "Есенино",
    slug: "esenino",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=c7abd71e-8513-11ed-b378-000c29e6a00e",
    direction: "Каширское шоссе",
    distance: 38,
    readiness: 95,
    description: "Уютный посёлок с природным окружением. Полная инфраструктура и все коммуникации.",
    features: ["Газ", "Электричество", "Асфальт", "Охрана", "Природа"],
    priceFrom: 420000,
    plotsCount: 40,
    plotsAvailable: 8,
    areaFrom: 6,
    areaTo: 10,
    photos: [
      `/villages/esenino/01.jpg`,
      `/villages/esenino/02.jpg`,
      `/villages/esenino/03.jpg`,
      `/villages/esenino/04.jpg`,
      `/villages/esenino/05.jpg`,
      `/villages/esenino/06.jpg`,
      `/villages/esenino/07.jpg`,
      `/villages/esenino/08.jpg`,
    ],
    coords: [55.2900, 37.8300],
    plots: [
      { id: 1101, number: "7", area: 6, price: 425000, status: "available" },
      { id: 1102, number: "15", area: 8, price: 420000, status: "available" },
      { id: 1103, number: "22", area: 10, price: 415000, status: "reserved" },
    ],
  },
  {
    id: 12,
    name: "Минаево Парк",
    slug: "minaevo-park",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=5051c987-4315-11ed-8ea5-00155d7faf0b",
    direction: "Каширское шоссе",
    distance: 40,
    readiness: 80,
    description: "Посёлок с парковой зоной. Развитая инфраструктура, школы и медицинские учреждения поблизости.",
    features: ["Газ", "Электричество", "Асфальт", "Парк", "Школы", "Медицина"],
    priceFrom: 380000,
    plotsCount: 50,
    plotsAvailable: 20,
    areaFrom: 6,
    areaTo: 12,
    photos: [
      `/villages/minaevo-park/01.jpg`,
      `/villages/minaevo-park/02.jpg`,
      `/villages/minaevo-park/03.jpg`,
      `/villages/minaevo-park/04.jpg`,
      `/villages/minaevo-park/05.jpg`,
      `/villages/minaevo-park/06.jpg`,
      `/villages/minaevo-park/07.jpg`,
      `/villages/minaevo-park/08.jpg`,
    ],
    coords: [55.2500, 37.8000],
    plots: [
      { id: 1201, number: "3", area: 6, price: 385000, status: "available" },
      { id: 1202, number: "14", area: 8, price: 380000, status: "available" },
      { id: 1203, number: "25", area: 10, price: 375000, status: "available" },
      { id: 1204, number: "36", area: 12, price: 370000, status: "reserved" },
    ],
  },
  {
    id: 13,
    name: "Лазурный",
    slug: "lazurny",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=dd45571f-40db-11ee-b3a7-000c29e6a00e",
    direction: "Каширское шоссе",
    distance: 38,
    readiness: 90,
    description: "Коттеджный посёлок с полным набором коммуникаций. 38 км от МКАД по Каширскому шоссе.",
    features: ["Газ", "Электричество", "Асфальт", "Охрана", "Все коммуникации"],
    priceFrom: 450000,
    plotsCount: 60,
    plotsAvailable: 15,
    areaFrom: 6,
    areaTo: 10,
    photos: [
      `/villages/lazurny/01.jpg`,
      `/villages/lazurny/02.jpg`,
      `/villages/lazurny/03.jpg`,
      `/villages/lazurny/04.jpg`,
      `/villages/lazurny/05.jpg`,
      `/villages/lazurny/06.jpg`,
      `/villages/lazurny/07.jpg`,
      `/villages/lazurny/08.jpg`,
    ],
    coords: [55.2700, 37.8100],
    plots: [
      { id: 1301, number: "5", area: 6, price: 455000, status: "available" },
      { id: 1302, number: "18", area: 8, price: 450000, status: "available" },
      { id: 1303, number: "30", area: 10, price: 445000, status: "reserved" },
    ],
  },
  {
    id: 14,
    name: "Династия",
    slug: "dinastiya",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=d6a6d68a-c568-11ec-8e96-00155d7faf0b",
    direction: "Каширское шоссе",
    distance: 41,
    readiness: 85,
    description: "Крупный посёлок на 257 участков. 70 гектаров леса, 41 км от МКАД по Каширскому шоссе.",
    features: ["Газ", "Электричество", "Асфальт", "Охрана", "Лес 70 га"],
    priceFrom: 350000,
    plotsCount: 257,
    plotsAvailable: 91,
    areaFrom: 5,
    areaTo: 12,
    photos: [
      `/villages/dinastiya/01.jpg`,
      `/villages/dinastiya/02.jpg`,
      `/villages/dinastiya/03.jpg`,
      `/villages/dinastiya/04.jpg`,
      `/villages/dinastiya/05.jpg`,
      `/villages/dinastiya/06.jpg`,
      `/villages/dinastiya/07.jpg`,
      `/villages/dinastiya/08.jpg`,
    ],
    coords: [55.2400, 37.7900],
    plots: [
      { id: 1401, number: "10", area: 5, price: 355000, status: "available" },
      { id: 1402, number: "50", area: 8, price: 350000, status: "available" },
      { id: 1403, number: "100", area: 10, price: 345000, status: "available" },
      { id: 1404, number: "150", area: 12, price: 340000, status: "reserved" },
    ],
  },
  {
    id: 15,
    name: "Calipso Village-2",
    slug: "calipso-village-2",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=abda6f53-fe62-11eb-944b-ac1f6b478593",
    direction: "Дмитровское шоссе",
    distance: 30,
    readiness: 95,
    description: "Посёлок на Дмитровском направлении с готовой инфраструктурой и всеми коммуникациями.",
    features: ["Газ", "Электричество", "Асфальт", "Охрана", "Все коммуникации"],
    priceFrom: 900000,
    plotsCount: 50,
    plotsAvailable: 12,
    areaFrom: 6,
    areaTo: 12,
    photos: [
      `/villages/calipso-village-2/01.jpg`,
      `/villages/calipso-village-2/02.jpg`,
      `/villages/calipso-village-2/03.jpg`,
      `/villages/calipso-village-2/04.jpg`,
      `/villages/calipso-village-2/05.jpg`,
      `/villages/calipso-village-2/06.jpg`,
      `/villages/calipso-village-2/07.jpg`,
      `/villages/calipso-village-2/08.jpg`,
    ],
    coords: [55.9600, 37.5500],
    plots: [
      { id: 1501, number: "8", area: 6, price: 905000, status: "available" },
      { id: 1502, number: "20", area: 8, price: 900000, status: "available" },
      { id: 1503, number: "35", area: 10, price: 895000, status: "reserved" },
    ],
  },
  {
    id: 16,
    name: "Новое Фелисово",
    slug: "novoe-felisovo",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=bcc4837d-4576-11ee-b3a7-000c29e6a00e",
    direction: "Дмитровское шоссе",
    distance: 26,
    readiness: 88,
    description: "Посёлок в 26 км от МКАД по Дмитровскому шоссе. Хорошая транспортная доступность.",
    features: ["Газ", "Электричество", "Асфальт", "Охрана", "Близость к Москве"],
    priceFrom: 1100000,
    plotsCount: 45,
    plotsAvailable: 15,
    areaFrom: 6,
    areaTo: 12,
    photos: [
      `/villages/novoe-felisovo/02.jpg`,
      `/villages/novoe-felisovo/01.jpg`,
      `/villages/novoe-felisovo/03.jpg`,
      `/villages/novoe-felisovo/04.jpg`,
      `/villages/novoe-felisovo/05.jpg`,
      `/villages/novoe-felisovo/06.jpg`,
      `/villages/novoe-felisovo/07.jpg`,
      `/villages/novoe-felisovo/08.jpg`,
    ],
    coords: [55.9500, 37.5300],
    plots: [
      { id: 1601, number: "5", area: 6, price: 1105000, status: "available" },
      { id: 1602, number: "15", area: 8, price: 1100000, status: "available" },
      { id: 1603, number: "25", area: 10, price: 1095000, status: "reserved" },
    ],
  },
  {
    id: 17,
    name: "Грибоедово",
    slug: "griboedovo",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=713aac36-cf21-11ee-b3ad-005056a6b235",
    direction: "Каширское шоссе",
    distance: 39,
    readiness: 92,
    description: "Посёлок с хорошей экологией на Каширском направлении. Все коммуникации подведены.",
    features: ["Газ", "Электричество", "Асфальт", "Охрана", "Экология"],
    priceFrom: 380000,
    plotsCount: 55,
    plotsAvailable: 18,
    areaFrom: 6,
    areaTo: 10,
    photos: [
      `/villages/griboedovo/01.jpg`,
      `/villages/griboedovo/02.jpg`,
      `/villages/griboedovo/03.jpg`,
      `/villages/griboedovo/04.jpg`,
      `/villages/griboedovo/05.jpg`,
      `/villages/griboedovo/06.jpg`,
      `/villages/griboedovo/07.jpg`,
      `/villages/griboedovo/08.jpg`,
    ],
    coords: [55.2600, 37.8200],
    plots: [
      { id: 1701, number: "4", area: 6, price: 385000, status: "available" },
      { id: 1702, number: "18", area: 8, price: 380000, status: "available" },
      { id: 1703, number: "30", area: 10, price: 375000, status: "reserved" },
    ],
  },
  {
    id: 18,
    name: "Станционный ИЖС",
    slug: "stantsionnyy",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=c8745794-c297-11ef-b3b6-005056a6b235",
    direction: "Каширское шоссе",
    distance: 35,
    readiness: 80,
    description: "Посёлок ИЖС с удобным расположением. Все коммуникации и развитая инфраструктура.",
    features: ["Газ", "Электричество", "Асфальт", "ИЖС", "Все коммуникации"],
    priceFrom: 500000,
    plotsCount: 40,
    plotsAvailable: 12,
    areaFrom: 6,
    areaTo: 10,
    photos: [
      `/villages/stantsionnyy/01.jpg`,
      `/villages/stantsionnyy/02.jpg`,
      `/villages/stantsionnyy/03.jpg`,
      `/villages/stantsionnyy/04.jpg`,
      `/villages/stantsionnyy/05.jpg`,
      `/villages/stantsionnyy/06.jpg`,
      `/villages/stantsionnyy/07.jpg`,
      `/villages/stantsionnyy/08.jpg`,
    ],
    coords: [55.3100, 37.8400],
    plots: [
      { id: 1801, number: "6", area: 6, price: 505000, status: "available" },
      { id: 1802, number: "15", area: 8, price: 500000, status: "available" },
      { id: 1803, number: "24", area: 10, price: 495000, status: "reserved" },
    ],
  },
  {
    id: 19,
    name: "Ильинское ИЖС",
    slug: "ilinskoe-izhs",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=ab4c6b00-cf54-11eb-944a-ac1f6b478593",
    direction: "Каширское шоссе",
    distance: 30,
    readiness: 98,
    description: "Готовый посёлок ИЖС в 30 км от МКАД. 174 участка, почти всё продано. Полная инфраструктура.",
    features: ["Газ", "Электричество", "Асфальт", "ИЖС", "Охрана"],
    priceFrom: 600000,
    plotsCount: 174,
    plotsAvailable: 2,
    areaFrom: 6,
    areaTo: 12,
    photos: [
      `/villages/ilinskoe-izhs/01.jpg`,
      `/villages/ilinskoe-izhs/02.jpg`,
      `/villages/ilinskoe-izhs/03.jpg`,
      `/villages/ilinskoe-izhs/04.jpg`,
      `/villages/ilinskoe-izhs/05.jpg`,
      `/villages/ilinskoe-izhs/06.jpg`,
      `/villages/ilinskoe-izhs/07.jpg`,
      `/villages/ilinskoe-izhs/08.jpg`,
    ],
    coords: [55.3200, 37.8500],
    plots: [
      { id: 1901, number: "120", area: 8, price: 605000, status: "available" },
      { id: 1902, number: "155", area: 10, price: 600000, status: "available" },
    ],
  },
  {
    id: 20,
    name: "Новое Растуново",
    slug: "novoe-rastunovo",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=d10c8c8a-cf1e-11ee-b3ad-005056a6b235",
    direction: "Каширское шоссе",
    distance: 40,
    readiness: 85,
    description: "Посёлок в живописном месте на Каширском направлении. Полный набор коммуникаций.",
    features: ["Газ", "Электричество", "Асфальт", "Охрана", "Природа"],
    priceFrom: 370000,
    plotsCount: 60,
    plotsAvailable: 25,
    areaFrom: 6,
    areaTo: 12,
    photos: [
      `/villages/novoe-rastunovo/01.jpg`,
      `/villages/novoe-rastunovo/02.jpg`,
      `/villages/novoe-rastunovo/03.jpg`,
      `/villages/novoe-rastunovo/04.jpg`,
      `/villages/novoe-rastunovo/05.jpg`,
      `/villages/novoe-rastunovo/06.jpg`,
      `/villages/novoe-rastunovo/07.jpg`,
      `/villages/novoe-rastunovo/08.jpg`,
    ],
    coords: [55.2500, 37.8100],
    plots: [
      { id: 2001, number: "8", area: 6, price: 375000, status: "available" },
      { id: 2002, number: "20", area: 8, price: 370000, status: "available" },
      { id: 2003, number: "35", area: 10, price: 365000, status: "available" },
      { id: 2004, number: "48", area: 12, price: 360000, status: "reserved" },
    ],
  },
  // === Посёлки 21–31: добрано с zemexx.ru (все Каширское шоссе, Домодедовский район) ===
  {
    id: 21,
    name: "Артемово ИЖС",
    slug: "artemovo-izhs",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=4a3d91d2-cf1d-11ee-b3ad-005056a6b235",
    direction: "Каширское шоссе",
    distance: 42,
    readiness: 60,
    description:
      "Коттеджный посёлок Артемово ИЖС в Домодедовском районе рядом с лесным массивом 40 га. Развитая инфраструктура и удобная транспортная доступность по Каширскому шоссе.",
    features: ["Электричество", "Асфальт", "Лес", "Охрана", "Инфраструктура"],
    priceFrom: 260000,
    plotsCount: 567,
    plotsAvailable: 323,
    areaFrom: 5,
    areaTo: 9.34,
    photos: [
      `/villages/artemovo-izhs/01.jpg`,
      `/villages/artemovo-izhs/02.jpg`,
      `/villages/artemovo-izhs/03.jpg`,
      `/villages/artemovo-izhs/04.jpg`,
      `/villages/artemovo-izhs/05.jpg`,
      `/villages/artemovo-izhs/06.jpg`,
      `/villages/artemovo-izhs/07.jpg`,
      `/villages/artemovo-izhs/08.jpg`,
    ],
    coords: [55.29, 37.86],
    plots: [],
  },
  {
    id: 22,
    name: "Брусникино",
    slug: "brusnikino",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=c95be78e-ce05-11ed-b39e-000c29e6a00e",
    direction: "Каширское шоссе",
    distance: 39,
    readiness: 60,
    description:
      "Посёлок «Брусникино» в 39 км от МКАД по Каширскому шоссе. К каждому участку подведено электричество, проложены внутрипоселковые дороги, рядом лесной массив 40 га.",
    features: ["Электричество", "Асфальт", "Лес", "Инфраструктура"],
    priceFrom: 273000,
    plotsCount: 320,
    plotsAvailable: 12,
    areaFrom: 6.18,
    areaTo: 10.78,
    photos: [
      `/villages/brusnikino/01.jpg`,
      `/villages/brusnikino/02.jpg`,
      `/villages/brusnikino/03.jpg`,
      `/villages/brusnikino/04.jpg`,
      `/villages/brusnikino/05.jpg`,
      `/villages/brusnikino/06.jpg`,
      `/villages/brusnikino/07.jpg`,
      `/villages/brusnikino/08.jpg`,
    ],
    coords: [55.29, 37.87],
    plots: [],
  },
  {
    id: 23,
    name: "Бунино",
    slug: "bunino",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=420c0d6b-84ee-11ed-b378-000c29e6a00e",
    direction: "Каширское шоссе",
    distance: 38,
    readiness: 100,
    description:
      "Готовый посёлок «Бунино» в 38 км от МКАД по Каширскому шоссе в Домодедовском районе. 1,5 км собственной набережной, полная инфраструктура и коммуникации.",
    features: ["Газ", "Электричество", "Асфальт", "Набережная", "Охрана"],
    priceFrom: 263000,
    plotsCount: 586,
    plotsAvailable: 98,
    areaFrom: 5,
    areaTo: 16.79,
    photos: [
      `/villages/bunino/01.jpg`,
      `/villages/bunino/02.jpg`,
      `/villages/bunino/03.jpg`,
      `/villages/bunino/04.jpg`,
      `/villages/bunino/05.jpg`,
      `/villages/bunino/06.jpg`,
      `/villages/bunino/07.jpg`,
      `/villages/bunino/08.jpg`,
    ],
    coords: [55.25, 37.9],
    plots: [],
  },
  {
    id: 24,
    name: "Калина",
    slug: "kalina",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=0336cf24-d3c9-11ed-b39e-000c29e6a00e",
    direction: "Каширское шоссе",
    distance: 44,
    readiness: 100,
    description:
      "Готовый посёлок «Калина» в 44 км от МКАД по Каширскому шоссе с выходом к реке Северка. 20 минут до МКАД на автомобиле.",
    features: ["Электричество", "Асфальт", "Река", "Охрана", "Инфраструктура"],
    priceFrom: 221000,
    plotsCount: 384,
    plotsAvailable: 111,
    areaFrom: 5,
    areaTo: 13.19,
    photos: [
      `/villages/kalina/01.jpg`,
      `/villages/kalina/02.jpg`,
      `/villages/kalina/03.jpg`,
      `/villages/kalina/04.jpg`,
      `/villages/kalina/05.jpg`,
      `/villages/kalina/06.jpg`,
      `/villages/kalina/07.jpg`,
      `/villages/kalina/08.jpg`,
    ],
    coords: [55.21, 37.91],
    plots: [],
  },
  {
    id: 25,
    name: "Лидер",
    slug: "lider",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=d78772d1-d395-11ed-b39e-000c29e6a00e",
    direction: "Каширское шоссе",
    distance: 40,
    readiness: 90,
    description:
      "Посёлок «Лидер» в 40 км от МКАД по Каширскому шоссе рядом с селом Юсупово. Расположен вблизи лесного массива 62 га и живописного водоёма.",
    features: ["Электричество", "Асфальт", "Лес", "Водоём", "Охрана"],
    priceFrom: 303000,
    plotsCount: 358,
    plotsAvailable: 83,
    areaFrom: 5.57,
    areaTo: 10.14,
    photos: [
      `/villages/lider/01.jpg`,
      `/villages/lider/02.jpg`,
      `/villages/lider/03.jpg`,
      `/villages/lider/04.jpg`,
      `/villages/lider/05.jpg`,
      `/villages/lider/06.jpg`,
      `/villages/lider/07.jpg`,
      `/villages/lider/08.jpg`,
    ],
    coords: [55.27, 37.75],
    plots: [],
  },
  {
    id: 26,
    name: "Минаево ИЖС",
    slug: "minaevo-izhs",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=ff3a232d-4900-11ec-944c-ac1f6b478593",
    direction: "Каширское шоссе",
    distance: 39,
    readiness: 100,
    description:
      "Готовый посёлок Минаево ИЖС в окружении лесного массива 70 га. 39 км от МКАД по Каширскому шоссе в Домодедовском районе.",
    features: ["Газ", "Электричество", "Асфальт", "Лес", "Охрана"],
    priceFrom: 220000,
    plotsCount: 393,
    plotsAvailable: 1,
    areaFrom: 10.25,
    areaTo: 10.25,
    photos: [
      `/villages/minaevo-izhs/01.jpg`,
      `/villages/minaevo-izhs/02.jpg`,
      `/villages/minaevo-izhs/03.jpg`,
      `/villages/minaevo-izhs/04.jpg`,
      `/villages/minaevo-izhs/05.jpg`,
      `/villages/minaevo-izhs/06.jpg`,
      `/villages/minaevo-izhs/07.jpg`,
      `/villages/minaevo-izhs/08.jpg`,
    ],
    coords: [55.27, 37.85],
    plots: [],
  },
  {
    id: 27,
    name: "Растуново ИЖС",
    slug: "rastunovo-izhs",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=ce31ed4f-772c-11ee-b3a8-005056a6b235",
    direction: "Каширское шоссе",
    distance: 39,
    readiness: 60,
    description:
      "Посёлок Растуново ИЖС в Барыбино, 39 км от МКАД по Каширскому шоссе. Рядом лесной массив 40 га и более 25 объектов инфраструктуры.",
    features: ["Электричество", "Асфальт", "Лес", "Охрана", "Инфраструктура"],
    priceFrom: 329000,
    plotsCount: 551,
    plotsAvailable: 240,
    areaFrom: 5,
    areaTo: 9.4,
    photos: [
      `/villages/rastunovo-izhs/01.jpg`,
      `/villages/rastunovo-izhs/02.jpg`,
      `/villages/rastunovo-izhs/03.jpg`,
      `/villages/rastunovo-izhs/04.jpg`,
      `/villages/rastunovo-izhs/05.jpg`,
      `/villages/rastunovo-izhs/06.jpg`,
      `/villages/rastunovo-izhs/07.jpg`,
      `/villages/rastunovo-izhs/08.jpg`,
    ],
    coords: [55.29, 37.86],
    plots: [],
  },
  {
    id: 28,
    name: "Регата",
    slug: "regata",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=86e7b016-5709-11eb-943c-ac1f6b478593",
    direction: "Каширское шоссе",
    distance: 38,
    readiness: 100,
    description:
      "Готовый коттеджный посёлок «Регата» в 38 км от МКАД по Каширскому шоссе. 2 км собственной береговой полосы и развитая инфраструктура.",
    features: ["Газ", "Электричество", "Асфальт", "Берег", "Охрана"],
    priceFrom: 440000,
    plotsCount: 197,
    plotsAvailable: 1,
    areaFrom: 7.62,
    areaTo: 7.62,
    photos: [
      `/villages/regata/01.jpg`,
      `/villages/regata/02.jpg`,
      `/villages/regata/03.jpg`,
      `/villages/regata/04.jpg`,
      `/villages/regata/05.jpg`,
      `/villages/regata/06.jpg`,
      `/villages/regata/07.jpg`,
      `/villages/regata/08.jpg`,
    ],
    coords: [55.28, 37.88],
    plots: [],
  },
  {
    id: 29,
    name: "Репино",
    slug: "repino",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=af867ccc-09b5-11ed-8e98-00155d7faf0b",
    direction: "Каширское шоссе",
    distance: 43,
    readiness: 90,
    description:
      "Посёлок «Репино» в 43 км от МКАД по Каширскому шоссе, рядом с ж/д станцией Барыбино. Лесной массив 90 га и выход на трассу М4.",
    features: ["Электричество", "Асфальт", "Лес", "Охрана", "Железная дорога"],
    priceFrom: 233000,
    plotsCount: 401,
    plotsAvailable: 64,
    areaFrom: 5.15,
    areaTo: 10.78,
    photos: [
      `/villages/repino/01.jpg`,
      `/villages/repino/02.jpg`,
      `/villages/repino/03.jpg`,
      `/villages/repino/04.jpg`,
      `/villages/repino/05.jpg`,
      `/villages/repino/06.jpg`,
      `/villages/repino/07.jpg`,
      `/villages/repino/08.jpg`,
    ],
    coords: [55.22, 37.93],
    plots: [],
  },
  {
    id: 30,
    name: "Суриково",
    slug: "surikovo",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=08b3e361-da76-11f0-b3d0-005056b0f2da",
    direction: "Каширское шоссе",
    distance: 43,
    readiness: 80,
    description:
      "Посёлок «Суриково» в 43 км от МКАД по Каширскому шоссе. Лесной массив 90 га, более 25 локаций для семейного и активного досуга.",
    features: ["Электричество", "Асфальт", "Лес", "Охрана", "Инфраструктура"],
    priceFrom: 197000,
    plotsCount: 402,
    plotsAvailable: 345,
    areaFrom: 5,
    areaTo: 12.05,
    photos: [
      `/villages/surikovo/01.jpg`,
      `/villages/surikovo/02.jpg`,
      `/villages/surikovo/03.jpg`,
      `/villages/surikovo/04.jpg`,
      `/villages/surikovo/05.jpg`,
      `/villages/surikovo/06.jpg`,
      `/villages/surikovo/07.jpg`,
      `/villages/surikovo/08.jpg`,
    ],
    coords: [55.22, 37.93],
    plots: [],
  },
  {
    id: 31,
    name: "Светлый",
    slug: "svetlyy",
    iframeMapUrl: "https://map.zemexx.ru/v2/index.php?village_id=caeb0cd8-c72c-11ed-b39b-000c29e6a00e",
    direction: "Каширское шоссе",
    distance: 49,
    readiness: 100,
    description:
      "Готовый посёлок «Светлый» в 49 км от МКАД в городском округе Домодедово. 350 м береговой линии реки Северка вдоль посёлка.",
    features: ["Электричество", "Асфальт", "Река", "Охрана", "Инфраструктура"],
    priceFrom: 194000,
    plotsCount: 263,
    plotsAvailable: 74,
    areaFrom: 6.94,
    areaTo: 8.66,
    photos: [
      `/villages/svetlyy/01.jpg`,
      `/villages/svetlyy/02.jpg`,
      `/villages/svetlyy/03.jpg`,
      `/villages/svetlyy/04.jpg`,
      `/villages/svetlyy/05.jpg`,
      `/villages/svetlyy/06.jpg`,
      `/villages/svetlyy/07.jpg`,
      `/villages/svetlyy/08.jpg`,
    ],
    coords: [55.18, 37.95],
    plots: [],
  },
];

export const reviews = [
  {
    id: 1,
    name: "Алексей и Мария К.",
    text: "Купили участок в посёлке Фаворит год назад. Сейчас уже заканчиваем строительство дома. Очень довольны выбором — тихое место, лес рядом, все коммуникации уже были подведены. Дети в восторге от природы!",
    rating: 5,
    village: "Фаворит",
  },
  {
    id: 2,
    name: "Дмитрий С.",
    text: "Брал участок как инвестицию в Дачной Практике-2 полтора года назад. За это время стоимость выросла на 30%. Все документы в порядке, сделка прошла быстро и прозрачно.",
    rating: 5,
    village: "Дачная Практика-2",
  },
  {
    id: 3,
    name: "Елена В.",
    text: "Долго выбирали посёлок для дачи. Остановились на Новом Сонино — привлекла река и лес. Не пожалели ни разу! Приезжаем каждые выходные, дорога отличная, 40 минут от дома.",
    rating: 5,
    village: "Новое Сонино",
  },
  {
    id: 4,
    name: "Сергей и Ольга Т.",
    text: "Переехали в Лесной остров на ПМЖ. Газ, свет — всё есть. Охрана работает круглосуточно, территория ухоженная. Соседи — молодые семьи, дети дружат. Лучшее решение в нашей жизни!",
    rating: 5,
    village: "Лесной остров",
  },
  {
    id: 5,
    name: "Игорь М.",
    text: "Покупал участок в Шишкино Лэнд. Понравилось, что рядом магазины и школа — не нужно далеко ездить. Помогли с оформлением, всё прошло гладко. Рекомендую!",
    rating: 4,
    village: "Шишкино Лэнд",
  },
];

export const steps = [
  {
    number: 1,
    title: "Консультация",
    description: "Свяжитесь с нами, расскажите о ваших пожеланиях. Мы подберём подходящие варианты участков.",
  },
  {
    number: 2,
    title: "Просмотр участка",
    description: "Организуем бесплатную экскурсию в посёлок. Покажем участок, инфраструктуру, ответим на все вопросы.",
  },
  {
    number: 3,
    title: "Бронирование",
    description: "Понравился участок? Забронируйте его, чтобы никто не перехватил. Бронь фиксирует цену.",
  },
  {
    number: 4,
    title: "Проверка документов",
    description: "Наши юристы подготовят полный пакет документов. Вы получите выписку из ЕГРН и все необходимые справки.",
  },
  {
    number: 5,
    title: "Оформление сделки",
    description: "Подписание договора, регистрация в Росреестре. Вы получаете свидетельство о собственности.",
  },
  {
    number: 6,
    title: "Ваш участок!",
    description: "Поздравляем! Вы — владелец земельного участка. Начинайте строить дом своей мечты.",
  },
];
