/**
 * Local-dev fallback when Postgres is unreachable. Returns realistic
 * sample leads so the admin UI can be reviewed without spinning up a DB.
 *
 * Hard-gate: only used when NODE_ENV !== "production" AND the DB call
 * actually threw. In production this module is shipped but never invoked.
 */

import type { Lead } from "@prisma/client";

const now = new Date();
const min = (n: number) => new Date(now.getTime() - n * 60 * 1000);
const hr = (n: number) => new Date(now.getTime() - n * 3600 * 1000);
const day = (n: number) => new Date(now.getTime() - n * 86400 * 1000);

export const DEV_MOCK_LEADS: Lead[] = [
  {
    id: "dev_mock_1",
    createdAt: min(12),
    updatedAt: min(12),
    name: "Анна Петрова",
    phone: "+79991234567",
    email: null,
    message: '[QUIZ_LEAD · homepage]\n{\n  "area": "7-10",\n  "budget": "2-3m",\n  "direction": "south",\n  "goal": "live",\n  "timing": "now"\n}',
    type: "VIEWING",
    status: "NEW",
    source: "WEBSITE",
    villageSlug: null,
    plotNumber: null,
    utmSource: "yandex",
    utmMedium: "cpc",
    utmCampaign: "spring2026",
    referer: "https://yandex.ru/search?text=земельный+участок",
    userAgent: "Mozilla/5.0",
    ipHash: "abc123",
    tgSent: true,
    tgSentAt: min(12),
    tgError: null,
    notes: null,
    contactedAt: null,
  },
  {
    id: "dev_mock_2",
    createdAt: hr(2),
    updatedAt: hr(1),
    name: "Игорь Соколов",
    phone: "+79859052555",
    email: "igor@example.com",
    message: "Хочу подобрать участок до 2 млн, 10 соток, рядом с трассой.",
    type: "PRESENTATION",
    status: "IN_PROGRESS",
    source: "WEBSITE",
    villageSlug: "favorit",
    plotNumber: "12",
    utmSource: null,
    utmMedium: null,
    utmCampaign: null,
    referer: "https://zem.plus/village/favorit",
    userAgent: "Mozilla/5.0",
    ipHash: "def456",
    tgSent: true,
    tgSentAt: hr(2),
    tgError: null,
    notes: null,
    contactedAt: null,
  },
  {
    id: "dev_mock_3",
    createdAt: hr(5),
    updatedAt: hr(5),
    name: "Мария",
    phone: "+74951234567",
    email: null,
    message: null,
    type: "MORTGAGE",
    status: "CONTACTED",
    source: "WEBSITE",
    villageSlug: "lesnoy-ostrov",
    plotNumber: null,
    utmSource: null,
    utmMedium: null,
    utmCampaign: null,
    referer: null,
    userAgent: "Mozilla/5.0",
    ipHash: "ghi789",
    tgSent: false,
    tgSentAt: null,
    tgError: "telegram 429: Too Many Requests",
    notes: null,
    contactedAt: null,
  },
  {
    id: "dev_mock_4",
    createdAt: day(1),
    updatedAt: day(1),
    name: "",
    phone: "+79161112233",
    email: null,
    message: null,
    type: "CALLBACK",
    status: "WON",
    source: "TELEGRAM_BOT",
    villageSlug: null,
    plotNumber: null,
    utmSource: null,
    utmMedium: null,
    utmCampaign: null,
    referer: null,
    userAgent: null,
    ipHash: null,
    tgSent: true,
    tgSentAt: day(1),
    tgError: null,
    notes: null,
    contactedAt: null,
  },
  {
    id: "dev_mock_5",
    createdAt: day(3),
    updatedAt: day(2),
    name: "Дмитрий Иванов",
    phone: "+79051234567",
    email: "dmitry@gmail.com",
    message: '[QUIZ_LEAD · homepage]\n{\n  "area": "10-15",\n  "budget": "3m+",\n  "direction": "any",\n  "goal": "build",\n  "timing": "season"\n}',
    type: "VIEWING",
    status: "QUALIFIED",
    source: "WEBSITE",
    villageSlug: "novoe-sonino",
    plotNumber: null,
    utmSource: "google",
    utmMedium: "organic",
    utmCampaign: null,
    referer: null,
    userAgent: "Mozilla/5.0",
    ipHash: "jkl012",
    tgSent: true,
    tgSentAt: day(3),
    tgError: null,
    notes: null,
    contactedAt: null,
  },
];
